### ISSUE TITLE
mbeans attribute for active sessions

### ISSUE THREAD

**Issue by minxas** [javamelody/jira-confluence-javamelody#14]
Hi,
I do have a question regarding active sessions count for jira in the graph. Which mbeans attribute is used to get this data?

**Comment by evernat** [comment]
I suppose that you are speaking about the graph of http sessions. It is not a mbean attribute.
It is computed by [SessionListener#getSessionCount()](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/SessionListener.java) with the help of [PluginMonitoringFilter](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/PluginMonitoringFilter.java) in the case of javamelody plugin for jira/confluence/bamboo/bitbucket.
