### ISSUE TITLE
Java melody for Jira 8.20.1

### ISSUE THREAD

**Issue by sduggineni-kpmg** [javamelody/jira-confluence-javamelody#15]
It seems, the plugin for Jira 8.20.1 LTS is not yet released. 
Do you have any plans to release   ?

**Comment by inaivelt** [comment]
Any news?
We also could not use the plugin for Jira 8.20.8.

**Comment by MaxPaw** [comment]
Same here, latest release not working

**Comment by evernat** [comment]
@sduggineni-kpmg jira is often telling wrong thing about compatibility, the plugin for Jira 8.20.1 was already released for both datacenter and server versions. You can see there for latest versions : https://marketplace.atlassian.com/apps/20909/javamelody-monitoring-plugin?tab=versions&hosting=datacenter

**Comment by evernat** [comment]
@inaivelt @MaxPaw not reproduced with Jira 8.20.8. Do you have an exception for javamelody in the logs ?

**Comment by evernat** [comment]
no response from the reporter at the moment, closing this issue while waiting for a response
