### ISSUE TITLE
Request to provide Java Melody supported plugin for JIRA Server version 8.20.10

### ISSUE THREAD

**Issue by arwavis** [javamelody/jira-confluence-javamelody#19]
Hi Team,

Due security alert we have upgraded our JIRA Server version to 8.20.10 and i dont see a supported java melody plugin for this version and the latest i see is 1.87.0 for Jira Server 4.3 - 8.19.1,
Confluence Server 3.2 - 7.13.8,
Bamboo Server 3.4 - 8.0.9,
Bitbucket Server 5.0.0 - 7.21.2

Could you please provide a supported plugin for JIRA Server Version 8.20.10?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Please advise if you have any update?

Regards
Aravind Viswanathan.

**Comment by evernat** [comment]
Atlassian marketplace is a bit strange,
See https://marketplace.atlassian.com/apps/20909/javamelody-monitoring-plugin/version-history to see information about versions.

And don't pay much attention to versions of this plugin in the marketplace : if a version x.y is displayed as compatible, version x.z some time later is also compatible.

Just install as said in the wiki and see that all is well : https://github.com/javamelody/javamelody/wiki/AtlassianPlugin

**Comment by arwavis** [comment]
Noted, Thanks.
