### ISSUE TITLE
Java melody issues with Jira

### ISSUE THREAD

**Issue by iVishy** [javamelody/jira-confluence-javamelody#20]
Hello,
After installing Java melody the application starts ok but data source details does not load. I have replaced the jdbc- data source with jndi.. as stated in the document. Replaced and added the db connection parameters in server xml. Upon restart the instance does not start and unable to connect to DB. 

Please can you assist what could be wrong ?

viswa

**Comment by evernat** [comment]
Hope you have resolved the issue by yourself.
Otherwise try to read again https://github.com/javamelody/javamelody/wiki/AtlassianPlugin
