### ISSUE TITLE
Upgrading Confluence to data center throws "Incompatible" error for javamelody add-on

### ISSUE THREAD

**Issue by poojaLsingh** [javamelody/jira-confluence-javamelody#22]
Hello Team,
We have recently upgraded our Server Jira and Confluence to DC versions and updated the them with community licenses.
We ran into an error from javamelody monitoring plugin which states that it is "incompatible".
We have requested update form the application but we need a resolution to this issue before we hit any repercussions on production.
Please let me know if we can do something about this also let me know if you need more information from my end.

Thanks in advance.
Kind Regards,
Pooja

**Comment by poojaLsingh** [comment]
Dear Support,
Any news on this?
Please let us know about this at earliest as the error is on production.
Kind Regards,
Pooja

**Comment by poojaLsingh** [comment]
Dear Support,
Please let me know if you have any update on this?
Thanks in advance.
Kind Regards,
Pooja

**Comment by evernat** [comment]
hello,
Which error exactly?

**Comment by evernat** [comment]
No answer from the reporter, so closing.
