### ISSUE TITLE
Confluence Server to Data Center conversion

### ISSUE THREAD

**Issue by rajain12** [javamelody/jira-confluence-javamelody#23]
Hi Team,

We are in process of upgrading our Jira & Confluence server to the Data Center version and have some queries with regards to the “JavaMelody Monitoring Plugin” plugin on the installation/conversion of plugin Data Center Conversion

Q1.  When we should upgrade the plugin, is it after the Jira & Confluence application has been
        converted to the Data Center version or we should upgrade the plugin first?
 
Q2.  Are we required to uninstall and install the data center version of the plugin or
       simply pasting the data center version license would work here?
 
Q3.  Is there any loss/change in the functionality of the plugin in the data center version?

Thanks,
Rahul Jain

**Comment by evernat** [comment]
Q1 the plugin is the same for server and data center. So there is no need to change it.

Q2 no need to uninstall and install

Q3 no change in the functionality of the plugin. But note, that the data of the monitoring page is from one instance independently of the data of the monitoring page of the other instance.

And the plugin is not currently listed in the atlassian marketplace for datacenter anymore, but it still works for datacenter like it was also working for datacenter before being listed in the atlassian marketplace for datacenter. It is just boring to periodically repeat atlassian certification process and to workaround the marketplace issues for an opensource plugin like this one.
