### ISSUE TITLE
Java Melody not working for Atlassian Crowd

### ISSUE THREAD

**Issue by vjaiswal101** [javamelody/jira-confluence-javamelody#25]
Hi,
I have installed Java Melody on Atlassain Crowd, similar to how its mentioned for Jira and Confluence here - https://github.com/javamelody/javamelody/wiki/AtlassianPlugin , but its not working.
Is Crowd not supported for Java Melody ?

**Comment by evernat** [comment]
yes Crowd is not supposed to be supported.
The javamelody monitoring plugin is known to work with JIRA. Confluence, Bamboo, Bitbucket.
See https://github.com/javamelody/javamelody/wiki/AtlassianPlugin
