### ISSUE TITLE
App functionality and support after Jira server EOL

### ISSUE THREAD

**Issue by amita140** [javamelody/jira-confluence-javamelody#29]
Hi,

Can you please confirm what will happen to the "JavaMelody Monitoring Plugin" apps after the Jira server EOL (if the server license is not renewed)?

Please let us know what all functionality will be affected.

Regards
Amita

**Comment by evernat** [comment]
The javamelody monitoring plugin does not care about the Jira server license, renewed or not. It will not change anything for the plugin.

**Comment by amita140** [comment]
Hi Thank you for the information. Will support or upgrades will be available?

Regards
Amita

**Comment by evernat** [comment]
yes
