### ISSUE TITLE
Java melody Plugin incompatible in JIRA Data center version 9.4.x

### ISSUE THREAD

**Issue by JeraldRobin** [javamelody/jira-confluence-javamelody#31]
Hi Team, we are in process of migration our JIRA server Version 9.4.x to JIRA data center version, and we see the java melody shows incompatible for the DC version.

Could you let us know how we can rectify this and continue using this plugin in DC version? .

Or is there an option to use the Server version plugin on DC version?

Will there be any issue or is there a plan to release DC version? ?

Please could you address this on priority.

Thanks
Jerald Robin

**Comment by evernat** [comment]
Hello @JeraldRobin 

The plugin is the same for server and data center.
And the plugin is not currently listed in the atlassian marketplace for datacenter anymore, but it still works for datacenter like it was also working for datacenter before being listed in the atlassian marketplace for datacenter. It is just boring to periodically repeat atlassian certification process and to workaround the marketplace issues for an opensource plugin like this one.

Just install as said in the wiki and see that all is well : https://github.com/javamelody/javamelody/wiki/AtlassianPlugin
