### ISSUE TITLE
Enabling Authentication for monitoring page in Bitbucket

### ISSUE THREAD

**Issue by sowmya-parsi** [javamelody/jira-confluence-javamelody#8]
I have installed the JavaMelody plugin for bitbucket as mentioned here : https://github.com/javamelody/javamelody/wiki/AtlassianPlugin and set the system property -Djavamelody.authorized-users=admin:pwd . Doing this authentication for the monitoring page is working fine but there is something conflicting in general bitbucket apllication authentication.Is there any way in which the monitoring uses bitbucket authentication only.

**Comment by evernat** [comment]
Issue moved to https://github.com/javamelody/jira-confluence-javamelody/issues/8

**Comment by evernat** [comment]
OK, I understand that after using the basic auth with username and password to access the monitoring page, the Bitbucket's auth has been affected. I reproduce that with Bitbucket v6.9.0.

I suggest to not save the javamelody username and password in the browser, if the browser proposes that, and I suggest to close the browser and all its windows when you have finished with the monitoring page.
That way, the Bitbucket authentication will not be affected.

**Comment by Torkuato** [comment]
Hi!

Same conflict with native login in Bitbucket **7.6.12**.

Have you planned fix this in future? Or there is nothing you can do.

Thank you.

**Comment by evernat** [comment]
@Torkuato 
It was said above for Bitbucket 6.9.0 and before :
> there is no easy access to the user from the http session and Bitbucket's AuthenticationContext does not give access to the user given the order of servlet filters

I suppose that the situation has not evolved with Bitbucket 7.6.12.
So no, there is no fix planned if the situation in Bitbucket does not evolve.

Note that when using authorized-users as said above to enable basic auth for the monitoring page, there is a workaround in order to not have a conflict with Bitbucket's auth :
> I suggest to not save the javamelody username and password in the browser, if the browser proposes that, and I suggest to close the browser and all its windows when you have finished with the monitoring page.
That way, the Bitbucket authentication will not be affected.

**Comment by evernat** [comment]
Auth for system admin is now done by Atlassian Platform 7 for the plugin after 42d7861 (to be released in 1.99.2).
So it shoud be enabled when using the plugin 1.99.2 or later, in Bitbucket 9 or later.
